### ISSUE TITLE
Future prices

### ISSUE THREAD

**Issue by DeVille70** [flopp999/Tibber-Domoticz#26]
Still very happy with what you provided on request Subscription #14 - works great.

Now I would like to optimize electric power usage costs (car charging, floor heating, water heating, etc) by using future prices. I understand that around noon every day Nord Pool releases hourly prices for all of the next day, and these prices are then available in the Tibber API.  So, at that time, the hourly prices for the rest of the day as well as the next 24 hours are known, and I would like to use that to switch some of my electric usage on and off accordingly. 

Not sure how to present it, as some additional 36 devices may not be very practical. Some sort of table, perhaps?

Thanks.

**Comment by eirikman** [comment]
Is it possible to utilize user variables? 36 variables with one price each, or make one user variable with a string containing all the prices.

**Comment by flopp999** [comment]
This plug-in will update the current price-device so you can use that value to control your house.
I am using this device to start/stop things.
There is also a mean price-device,  this one I use start/stop my pool heater

**Comment by DeVille70** [comment]
Yes, agree that current price and mean price is available for control. Happy with that. But https://developer.tibber.com/explorer, using example query "Current energy price", also gives price for each hour for the rest of the day and tomorrow. That really gives you the possibility to plan your energy consumption.

**Comment by flopp999** [comment]
Hi, I have maybe solved this. But not in Tibber Plugin.
I have created a python script that get data from NordPool and then create 24 devices, one for each hour. Updates every midnight.
https://github.com/flopp999/NordPool-InfluxDB
Look like this
![image](https://user-images.githubusercontent.com/21694965/132957796-29104eb3-ba50-408b-a104-56cd80043a51.png)

**Comment by DeVille70** [comment]
Thanks a lot. I am very busy a the moment, but I will definitely look into this.

**Comment by flopp999** [comment]
This plugin will create devices for each hour and also a few other devices.

https://github.com/flopp999/NordPoolSpotPrice-Domoticz

**Comment by DeVille70** [comment]
Very sorry, I have not had the time to look at this yet... :(

**Comment by flopp999** [comment]
Happy with the solution?

**Comment by DeVille70** [comment]
Still have not tried it, and to be honest I don't think I will use it. My approach to this has changed. Still bough you a coffee, though, for your great help. 👍
