### ISSUE TITLE
Watt device shows zero when export is greater than import

### ISSUE THREAD

**Issue by Skjal** [flopp999/Tibber-Domoticz#30]
When my solar panels are generating more power than the house consuming, the watt meter device shows zero while in the Tibber app it show how much power that is exported. According to Tibber customer service, power export is updated every 10th second. Would it be possible to create a device for export as well? It would be handy in terms of turning on/off power consuming devices according to what you have of available power. I think it is called powerproduction in the api.

**Comment by flopp999** [comment]
Hi
What version of plug-in do you use?
Can you see how much power you sell, in Tibber Developer web page?
https://developer.tibber.com/explorer

**Comment by Skjal** [comment]
Thanks for looking into this.

I am using version 0.93. 


According to the Tibber developer api guide, the live measurement/powerProduction should be updated every 10 seconds with  the value of what you export.  here is a screenshot of my developer web page but without any export since it is a bit late in the afternoon and not enough sun to get any export. Can try to get one tomorrow afternoon if it would help.
![image](https://user-images.githubusercontent.com/88674209/128742318-8f7115a5-2a03-4281-9df8-70e2c97694b8.png)

**Comment by flopp999** [comment]
I will take a look at this today.
Can you send me a message on Domoticz Forum?

**Comment by Skjal** [comment]
Working great now after last update. Thanjs
