### ISSUE TITLE
It is not possible vizualise the tibber sensor values with gauges in HomeHabit

### ISSUE THREAD

**Issue by swejmansson** [flopp999/Tibber-Domoticz#42]
I´m using HomeHabit app on android tablets to represent data from Domoticz.
For some reason it is not possible to vizualise the tibber sensor values with gauges.
Are the values in the sensors stored as strings?
When I show them with the value-tool in HomeHabit it writes out the value with unit, like "2234 w". Must be a string 🤔
If it is strings, are you planning to correct it and store as number/flowt?
The way around it for me can be to mask/convert them to fit my use case, but it would be better to do it "correct" from the beginning. Most likely some more users can bump into issues when they want to use/display the values 🙄

![image](https://user-images.githubusercontent.com/45631337/137798876-93f761b4-a24b-4c04-989e-7066e2faded0.png)

**Comment by flopp999** [comment]
Data must be String when using Custom Sensor, as I do.
https://www.domoticz.com/wiki/Developing_a_Python_plugin#Devices
I have tried to use other SubTypes but then i could not push data to InfluxDB. I will try again and see if I made a mistake last time.

**Comment by swejmansson** [comment]
Let me know if you want me to verrify 👍
