### ISSUE TITLE
Feature request: Add a toggle for turning on/off Pulse/Watty data subscription

### ISSUE THREAD

**Issue by swejmansson** [flopp999/Tibber-Domoticz#47]
I have a Tibber Pulse installed and use it as a balancer for the EV car charging. 
For now I have no use of the data provided by Pulse in Domoticz.
It would be good if it was possible to turn off/on the data subscription in the plugin. Just like you can select "kr" or "öre".
This is not a huge issue and there is no big need for the feature, but if it was available I would have used it to turn the data off 😃
Thanks for great work on the plugin 💪

/Jens

**Comment by flopp999** [comment]
Version 1.14 have a selector for creating devices for Realtime.
I have 1.14 in a different branch
https://github.com/flopp999/Tibber-Domoticz/blob/beta/plugin.py
When 1.13 is confirmed to work I will move 1.14 to Main branch

**Comment by swejmansson** [comment]
Great news! Thanks 🎩🤝
