### ISSUE TITLE
Domoticz freeze

### ISSUE THREAD

**Issue by Gladden63** [flopp999/Tibber-Domoticz#5]
After implementation of plugin and reboot I tried to configure hardware and input my Tibber api key. Then Domotoc freeze. Unable to recover unless I remove the plugin.py file and restart.

Is there any logs?

**Comment by flopp999** [comment]
Sorry, no logs at the moment.

Are you running on Linux or Windows?

If on Windows, do you start Domoticz as Admin with full rights in the installation folder?
