### ISSUE TITLE
Retrieve Home ID

### ISSUE THREAD

**Issue by jupstra** [flopp999/Tibber-Domoticz#55]
Hi, 

Thanks for this nice plugin, got it up and running. Finding the home-id took me a little while though, maybe you could extend the instructions with something like:

"Go to the API explorer and run the following:`{
  viewer {
    homes {
      id
      timeZone
      address {
        address1
        postalCode
        city
      }
    }
  }
}`"

Keep up the good work!

**Comment by flopp999** [comment]
Thanks, I have now updated the README.
Do you think this will help? :)
