### ISSUE TITLE
No new devices created

### ISSUE THREAD

**Issue by evanhemmen** [flopp999/Tibber-Domoticz#57]
Hi, I saw that about a year ago a similar issue was closed as it solved itself but I'm afraid my issue is not solving itself.

I istalled the plugin v1.2.0 as per instructions on my Domoticz v2022.1 on a Raspberry Pi running Raspbian. No new devices are created (restarting or rebooting Domoticz doesn't help either).

Both Domoticz log as Tibber.log do not show any errors. 

![Tibberlog](https://user-images.githubusercontent.com/76887498/210139904-7c272a85-cc39-4963-8569-080bed60a710.jpg)

Any suggestions?

Edit:
If I use the Demo Token Domoticz log is showing some errors:

```
2022-12-31 15:29:22.696 Error: Tibber: 'onMessage' failed 'IndexError':'list index out of range'.
2022-12-31 15:29:22.696 Error: Tibber: Exception traceback:
2022-12-31 15:29:22.696 Error: Tibber: ----> Line 535 in '/home/pi/domoticz/plugins/Tibber-Domoticz/plugin.py', function onMessage
2022-12-31 15:29:22.696 Error: Tibber: ----> Line 269 in '/home/pi/domoticz/plugins/Tibber-Domoticz/plugin.py', function onMessage 
```

**Comment by belzig** [comment]
Same with me.
No device created.

Version: 2022.1 (build 14318)
Build Hash: a380461ea
Compile Date: 2022-04-22 07:36:31
dzVents Version: 3.1.8
Python Version: 3.9.2 (default, Mar 12 2021, 04:06:34) [GCC 10.2.1 20210110]

**Comment by flopp999** [comment]
Thanks for creating an issue.
I have now fix it. It was wrong Demo token.
If you had copied your own Token it should have worked.
Did you change the token?

**Comment by belzig** [comment]
Hi,
now it works like a charm with the demotoken.

With my own token,  still no new devices show up.
I think it`s  because my contract hasn`t be confirmed yet. I`ll try again when it ist confirmed and Pulse IR is delivered.

Thanks for your work

**Comment by evanhemmen** [comment]
Hi, thanks for the update, unfortunately still no success here. I reinstalled the plugin, it is now v1.22. I followed the instructions to install again, but stillno devices are added. Within Domoticz I get the following error messages in the log:
![Error Domoticz Tibber](https://user-images.githubusercontent.com/76887498/210864689-67e03ce7-dfca-4892-a909-dc42bb20f0df.jpg)

The Tibber.log seems clean, no error messages there:
![Tibberlog](https://user-images.githubusercontent.com/76887498/210864753-ce111df6-9710-419e-b8dd-7cefa4efa838.jpg)

I use the Tibber demo token:
5K4MVS-OjfWhK_4yrjOlFe1F6kJXPVf7eQYggo8ebAE

And the home id related to the demo token:
96a14971-525a-4420-aae9-e5aedaa129ff

**Comment by JanvdW304** [comment]
I have the same issue, and I think that the plugin only works the moment that the contract is started. Till then the realTimeConsumptionEnabled element is false which lead to the error message "No real time hardware is installed". See my [issue](https://github.com/flopp999/Tibber-Domoticz/issues/56) for details

**Comment by evanhemmen** [comment]
Thanks for the info. This could be the reason as my contract starts 14th of January. In the Tibber app I already see the tariffs so I thought it would be available to me via the api as wel. I'll wait and report back after the 14th.

**Comment by flopp999** [comment]
It should with Demo token. Do you get devices when using Demo token?

**Comment by belzig** [comment]
If you want to use the demotoken, go to Tibber api Explorer.
https://developer.tibber.com/explorer  -> Load Demotoken 

Try this query

{
  viewer {
    homes {
      id
      address {
        address1
        address2
        address3
        postalCode
        city
        country
        latitude
        longitude
      }
    }
  }
}
Then you shoud get this output

{
  "data": {
    "viewer": {
      "homes": [
        {
          "id": "96a14971-525a-4420-aae9-e5aedaa129ff",
          "address": {
            "address1": "Winterfell Castle 1",
            "address2": null,
            "address3": null,
            "postalCode": null,
            "city": null,
            "country": null,
            "latitude": null,
            "longitude": null
          }
        }
      ]
    }
  }
}

The creditals for Domotics are then
Token  5K4MVS-OjfWhK_4yrjOlFe1F6kJXPVf7eQYggo8ebAE  <- Thats the demotoken
HomeID 96a14971-525a-4420-aae9-e5aedaa129ff   <-Thats the ID provided by the query

Then a awfull lot of devices will be created. 
No worry, they will be deleted when you delete the Tibber Api 2.0 in Hardware Folder

Hope it helps

**Comment by flopp999** [comment]
You don't need to create an account to be able to use the Demo token.

**Comment by belzig** [comment]
You need an account to run the query in Tibber Api Explorer

**Comment by evanhemmen** [comment]
> It should with Demo token. Do you get devices when using Demo token?

Yes devices appeared with demo token. 

Another question: will the currency change to Euro and the tariff to Netherlands when I use my own Token and Home ID?

**Comment by flopp999** [comment]
> > It should with Demo token. Do you get devices when using Demo token?
> 
> 
> 
> Yes devices appeared with demo token. 
> 
> 
> 
> Another question: will the currency change to Euro and the tariff to Netherlands when I use my own Token and Home ID?

Good question. I didn't know that Tibber existed in the Netherlands.

**Comment by evanhemmen** [comment]
Hahaha, now you know :-).

I’ll let you know what happens when my contract starts 14th of January.

**Comment by me-processware** [comment]
> > > It should with Demo token. Do you get devices when using Demo token?
> > 
> > 
> > Yes devices appeared with demo token.
> > Another question: will the currency change to Euro and the tariff to Netherlands when I use my own Token and Home ID?
> 
> Good question. I didn't know that Tibber existed in the Netherlands.

+1 on the EUR part :) i'am from the netherlands also.

bigger problem is the plugin stopped today again @ 12:59 pm (a default let's brake things on the api side?) 

2023-01-11 01:38:30.052404 onHeartbeat
2023-01-11 01:38:30.052567 onHeartbeatLivePowerEvery
2023-01-11 01:38:30.210266 Something went wrong during fetching Live Power from Tibber
2023-01-11 01:38:30.210394 received 4400 (private use) User-agent HTTP header or userAgent property within connectionParams missing or not informative enough; value 'user_agent'; then sent 4400 (private use) User-agent HTTP header or userAgent property within connectionParams missing or not informative enough; value 'user_agent'

**Comment by Sicco74** [comment]
> Hahaha, now you know :-).
> 
> I’ll let you know what happens when my contract starts 14th of January.

I am also curious, also NL and starting the 1st of Feb...

**Comment by Sicco74** [comment]
> > > It should with Demo token. Do you get devices when using Demo token?
> > 
> > 
> > Yes devices appeared with demo token.
> > Another question: will the currency change to Euro and the tariff to Netherlands when I use my own Token and Home ID?
> 
> Good question. I didn't know that Tibber existed in the Netherlands.

Yes, I am starting from the 1st of Feb and also would like Dutch prices and Euro :-).

**Comment by me-processware** [comment]
> > > > It should with Demo token. Do you get devices when using Demo token?
> > > 
> > > 
> > > Yes devices appeared with demo token.
> > > Another question: will the currency change to Euro and the tariff to Netherlands when I use my own Token and Home ID?
> > 
> > 
> > Good question. I didn't know that Tibber existed in the Netherlands.
> 
> +1 on the EUR part :) i'am from the netherlands also.
> 
> bigger problem is the plugin stopped today again @ 12:59 pm (a default let's brake things on the api side?)
> 
> 2023-01-11 01:38:30.052404 onHeartbeat 2023-01-11 01:38:30.052567 onHeartbeatLivePowerEvery 2023-01-11 01:38:30.210266 Something went wrong during fetching Live Power from Tibber 2023-01-11 01:38:30.210394 received 4400 (private use) User-agent HTTP header or userAgent property within connectionParams missing or not informative enough; value 'user_agent'; then sent 4400 (private use) User-agent HTTP header or userAgent property within connectionParams missing or not informative enough; value 'user_agent'

i found the error and fixed it here https://github.com/me-processware/Tibber-Domoticz/commit/8dfa3fbbe97c61eba635e047e9c3ff0e165c6a7c

**Comment by flopp999** [comment]
It works for me with User-Agent.
If you got time you are welcome to do a PR 😀

**Comment by me-processware** [comment]
> It works for me with User-Agent. If you got time you are welcome to do a PR 😀

done i had to google that. never done it before

**Comment by evanhemmen** [comment]
I promised to report back. My contract started today and now values are being updated based on my personal token and location-id.

Wrt euro's/€... In Domoticz you can edit the device and add €/kWh to the name and axis-label. Works perfect now!

![Schermafbeelding 2023-01-14 143505](https://user-images.githubusercontent.com/76887498/212474521-2020e0b8-dfa6-47d9-bab8-116d12e5f1ca.jpg)
